#!/usr/bin/env python3
"""Generate substitution_dicts.rs from the dictionaries defined below.

Usage:
    python3 scripts/generate_dicts.py           # print to stdout
    python3 scripts/generate_dicts.py --write    # overwrite src-tauri/src/substitution_dicts.rs
"""

import argparse
from pathlib import Path

ESCAPE_STR = "slash"

OUTPUT_PATH = Path(__file__).resolve().parent.parent / "src-tauri" / "src" / "substitution_dicts.rs"

# ──────────────────────────────────────────────
#  BASIC: spoken punctuation commands → symbols
# ──────────────────────────────────────────────
# Each (command, symbol) pair generates TWO entries:
#   "ESCAPE_STR <command>" → "<command>"   (escape hatch)
#   "<command>"         → "<symbol>"    (the substitution)

BASIC_COMMANDS = [
    ("comma",             ","),
    ("period",            "."),
    ("tab",               "\t"),
    ("line break",        "\n"),
    ("open quote",        '"'),
    ("close quote",       '"'),
    ("open paren",        "("),
    ("close paren",       ")"),
    ("open bracket",      "["),
    ("close bracket",     "]"),
    ("exclamation point", "!"),
    ("question mark",     "?"),
    ("colon",             ":"),
    ("semicolon",         ";"),
    ("dot dot dot",       "…"),
    ("backslash",         "\\"),
    ("forward slash",     "/"),
]

# Commands whose symbols should attach to the preceding word (no space before).
# When generating bare-command patterns, the pattern for these gets a leading
# space so the Aho-Corasick match consumes it, e.g. " comma" → ","
NO_SPACE_BEFORE = {
    "comma", "period", "exclamation point", "question mark",
    "colon", "semicolon", "close paren", "close bracket",
    "close quote", "dot dot dot",
}

# Commands where STT may already insert the symbol, so saying the command
# would produce a duplicate.  Generates e.g. ", comma" → "," to absorb it.
PUNCTUATION_DUP_PREVENT = ["comma", "period", "question mark"]

# ──────────────────────────────────────────────
#  PECULIAR: special character names → symbols
# ──────────────────────────────────────────────

PECULIAR = [
    ("alpha", "α"),
    ("beta",  "β"),
    ("right arrow", "⟶"),
    ("for all", "∀"),
    ("exists", "∃"),
    ("cap", "⋂"),
    ("cup", "⋃"),
    ("in", "∈"),
    ("integers", "ℤ"),
    ("naturals", "ℕ"),
    ("reals", "ℝ"),
    ("greater than", ">"),
    ("less than", "<"),
    ("at least", "≥"),
    ("at most", "≤"),

]

PECULIAR_NEED_ESCAPE = {
    "alpha", "beta",
    "for all", "exists",
    "cap", "cup", "in",
    "integers", "naturals", "reals",
    "greater than", "less than", "at least", "at most",
}

def rust_str(s: str) -> str:
    """Escape a string for a Rust string literal."""
    return (
        s.replace("\\", "\\\\")
        .replace('"', '\\"')
        .replace("\t", "\\t")
        .replace("\n", "\\n")
    )


def generate() -> str:
    lines = [
        "// @generated by scripts/generate_dicts.py — do not edit by hand.",
        "",
    ]

    # --- Basic ---
    basic_patterns = []
    basic_replacements = []

    # Escape hatches first ("ESCAPE_STR X" → word X)
    for cmd, _sym in BASIC_COMMANDS:
        basic_patterns.append(f"{ESCAPE_STR} {cmd}")
        basic_replacements.append(cmd)

    # Bare commands ("X" → symbol)
    # For NO_SPACE_BEFORE commands the pattern includes a leading space so the
    # Aho-Corasick match consumes it, producing e.g. "hello," instead of "hello ,"
    for cmd, sym in BASIC_COMMANDS:
        if cmd in NO_SPACE_BEFORE:
            basic_patterns.append(f" {cmd}")
        else:
            basic_patterns.append(cmd)
        basic_replacements.append(sym)

    # Duplicate-prevention: absorb "symbol + spoken command" when STT already
    # inserted the punctuation, e.g. ", comma" → ","
    sym_of = dict(BASIC_COMMANDS)
    for cmd in PUNCTUATION_DUP_PREVENT:
        sym = sym_of[cmd]
        basic_patterns.append(f"{sym} {cmd}")
        basic_replacements.append(sym)

    lines.append("#[cfg(test)]")
    lines.append("/// Escape token, for use in Rust tests.")
    lines.append(f'pub(crate) const ESCAPE_STR: &str = "{rust_str(ESCAPE_STR)}";')

    lines.append("/// Basic substitution patterns: spoken punctuation commands.")
    lines.append(f"/// Includes \"{ESCAPE_STR} X\" escape hatches.")
    lines.append("pub(crate) static BASIC_PATTERNS: &[&str] = &[")
    for p in basic_patterns:
        lines.append(f'    "{rust_str(p)}",')
    lines.append("];")
    lines.append("")

    lines.append("/// Replacements for basic patterns (parallel to BASIC_PATTERNS).")
    lines.append("pub(crate) static BASIC_REPLACEMENTS: &[&str] = &[")
    for r in basic_replacements:
        lines.append(f'    "{rust_str(r)}",')
    lines.append("];")
    lines.append("")

    # --- Peculiar ---
    lines.append("/// Peculiar substitution patterns: special character names.")
    lines.append("pub(crate) static PECULIAR_PATTERNS: &[&str] = &[")
    for cmd, _sym in PECULIAR:
        if cmd in PECULIAR_NEED_ESCAPE:
            lines.append(f'    "{rust_str(ESCAPE_STR)} {rust_str(cmd)}",')
        else:
            lines.append(f'    "{rust_str(cmd)}",')
    lines.append("];")
    lines.append("")

    lines.append("/// Replacements for peculiar patterns (parallel to PECULIAR_PATTERNS).")
    lines.append("pub(crate) static PECULIAR_REPLACEMENTS: &[&str] = &[")
    for _cmd, sym in PECULIAR:
        lines.append(f'    "{rust_str(sym)}",')
    lines.append("];")
    lines.append("")

    return "\n".join(lines)


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--write", action="store_true",
                        help="overwrite src-tauri/src/substitution_dicts.rs in-place")
    args = parser.parse_args()

    output = generate()
    if args.write:
        OUTPUT_PATH.write_text(output + "\n")
        print(f"wrote {OUTPUT_PATH}")
    else:
        print(output)
