#!/usr/bin/env python3
"""Generate substitution_dicts.rs from the dictionaries defined below.

Usage:
    python3 scripts/generate_dicts.py           # print to stdout
    python3 scripts/generate_dicts.py --write    # overwrite src-tauri/src/substitution_dicts.rs
"""

import argparse
from pathlib import Path
from typing import Optional

ESCAPE_STR = "slash"

# When non-None, BASIC dict switches to escape-only mode where commands require
# the prefix word (e.g., "add comma" → ","). Generates 32 combinations per command
# to handle Whisper's unpredictable punctuation insertion and pause-induced commas.
ESCAPE_ONLY_BASIC: Optional[str] = "add"

OUTPUT_PATH = Path(__file__).resolve().parent.parent / "src-tauri" / "src" / "substitution_dicts.rs"

# ──────────────────────────────────────────────
#  BASIC: spoken punctuation commands → symbols
# ──────────────────────────────────────────────
# When ESCAPE_ONLY_BASIC is None: each (command, symbol) pair generates TWO entries:
#   "ESCAPE_STR <command>" → "<command>"   (escape hatch)
#   "<command>"         → "<symbol>"    (the substitution)
#
# When ESCAPE_ONLY_BASIC is set (e.g., "add"): generates 32 combinations per command
# to handle Whisper's unpredictable punctuation insertion and pause-induced commas:
#   "{ld}add {command}{rd}"  → "<symbol>"   for all ld,rd in ["", ",", ".", " "]
#   "{ld}add, {command}{rd}" → "<symbol>"   for all ld,rd in ["", ",", ".", " "]

BASIC_COMMANDS = [
    ("comma",             ","),
    ("period",            "."),
    ("tab",               "\t"),
    ("line break",        "\n"),
    ("double quote",      '"'),
    ("single quote",      "'"),
    ("open paren",        "("),
    ("close paren",       ")"),
    ("closed paren",       ")"),
    ("open bracket",      "["),
    ("close bracket",     "]"),
    ("exclamation point", "!"),
    ("question mark",     "?"),
    ("colon",             ":"),
    ("semicolon",         ";"),
    ("dot dot dot",       "…"),
    ("backslash",         "\\"),
    ("forward slash",     "/"),
]

# Commands whose symbols should attach to the preceding word (no space before).
# When generating bare-command patterns, the pattern for these gets a leading
# space so the Aho-Corasick match consumes it, e.g. " comma" → ","
NO_SPACE_BEFORE = {
    "comma", "period", "exclamation point", "question mark",
    "colon", "semicolon", "close paren", "close bracket",
    "dot dot dot",
}

# Commands where STT may already insert the symbol, so saying the command
# would produce a duplicate.  Generates e.g. ", comma" → "," to absorb it.
PUNCTUATION_DUP_PREVENT = ["comma", "period", "question mark"]

# ──────────────────────────────────────────────
#  MATH_ESCAPED / MATH_MODE: math symbol names
# ──────────────────────────────────────────────
# MATH_ESCAPED: default mode, common-English commands require ESCAPE_STR prefix.
# MATH_MODE: activated by saying "math mode", all commands are bare (no prefix).

MATH_MODE_TRIGGER = "math mode"

MATH_ESCAPED = [
    ("alpha", "α"),
    ("beta",  "β"),
    ("right arrow", "⟶"),
    ("for all", "∀"),
    ("exists", "∃"),
    ("cap", "⋂"),
    ("cup", "⋃"),
    ("in", "∈"),
    ("integers", "ℤ"),
    ("naturals", "ℕ"),
    ("reals", "ℝ"),
    ("greater than", ">"),
    ("less than", "<"),
    ("at least", "≥"),
    ("at most", "≤"),
]

MATH_NEED_ESCAPE = {
    "alpha", "beta",
    "for all", "exists",
    "cap", "cup", "in",
    "integers", "naturals", "reals",
    "greater than", "less than", "at least", "at most",
}

def rust_str(s: str) -> str:
    """Escape a string for a Rust string literal."""
    return (
        s.replace("\\", "\\\\")
        .replace('"', '\\"')
        .replace("\t", "\\t")
        .replace("\n", "\\n")
    )


def generate() -> str:
    lines = [
        "// @generated by scripts/generate_dicts.py — do not edit by hand.",
        "",
    ]

    # --- Basic ---
    basic_patterns = []
    basic_replacements = []

    if ESCAPE_ONLY_BASIC is not None:
        # Escape-only mode: generate all 16 prefix/suffix combinations to handle
        # Whisper's unpredictable punctuation insertion around spoken commands.
        # Pattern: "{ld}{ESCAPE_ONLY_BASIC} {keyword}{rd}" → symbol
        # Also generate "add," variants (32 total) to handle pauses between words.
        affixes = ["", ",", ".", " "]
        for cmd, sym in BASIC_COMMANDS:
            for ld in affixes:
                for rd in affixes:
                    # Base pattern: "add <cmd>"
                    basic_patterns.append(f"{ld}{ESCAPE_ONLY_BASIC} {cmd}{rd}")
                    basic_replacements.append(sym)
                    # Pause-handling pattern: "add, <cmd>"
                    basic_patterns.append(f"{ld}{ESCAPE_ONLY_BASIC}, {cmd}{rd}")
                    basic_replacements.append(sym)

        # Duplicate-prevention: absorb "symbol + spoken command" when STT already
        # inserted the symbol, e.g. "? add question mark" → "?"
        # (Only needed for symbols not in affixes list above)
        sym_of = dict(BASIC_COMMANDS)
        for cmd in PUNCTUATION_DUP_PREVENT:
            sym = sym_of[cmd]
            if sym not in affixes:
                basic_patterns.append(f"{sym} {ESCAPE_ONLY_BASIC} {cmd}")
                basic_replacements.append(sym)
                # Also handle with comma after ESCAPE_ONLY_BASIC
                basic_patterns.append(f"{sym} {ESCAPE_ONLY_BASIC}, {cmd}")
                basic_replacements.append(sym)
    else:
        # Original mode: bare commands with escape hatches
        # Escape hatches first ("ESCAPE_STR X" → word X)
        for cmd, _sym in BASIC_COMMANDS:
            basic_patterns.append(f"{ESCAPE_STR} {cmd}")
            basic_replacements.append(cmd)

        # Bare commands ("X" → symbol)
        # For NO_SPACE_BEFORE commands the pattern includes a leading space so the
        # Aho-Corasick match consumes it, producing e.g. "hello," instead of "hello ,"
        for cmd, sym in BASIC_COMMANDS:
            if cmd in NO_SPACE_BEFORE:
                basic_patterns.append(f" {cmd}")
            else:
                basic_patterns.append(cmd)
            basic_replacements.append(sym)

        # Duplicate-prevention: absorb "symbol + spoken command" when STT already
        # inserted the punctuation, e.g. ", comma" → ","
        sym_of = dict(BASIC_COMMANDS)
        for cmd in PUNCTUATION_DUP_PREVENT:
            sym = sym_of[cmd]
            basic_patterns.append(f"{sym} {cmd}")
            basic_replacements.append(sym)

    lines.append("#[cfg(test)]")
    lines.append("/// Escape token, for use in Rust tests.")
    lines.append(f'pub(crate) const ESCAPE_STR: &str = "{rust_str(ESCAPE_STR)}";')

    if ESCAPE_ONLY_BASIC is not None:
        lines.append("/// Basic substitution patterns: escape-only mode.")
        lines.append(f'/// Requires \"{ESCAPE_ONLY_BASIC} <command>\" prefix, with 32 affix combinations')
        lines.append("/// to handle Whisper's unpredictable punctuation insertion and pause-induced commas.")
    else:
        lines.append("/// Basic substitution patterns: spoken punctuation commands.")
        lines.append(f"/// Includes \"{ESCAPE_STR} X\" escape hatches.")
    lines.append("pub(crate) static BASIC_PATTERNS: &[&str] = &[")
    for p in basic_patterns:
        lines.append(f'    "{rust_str(p)}",')
    lines.append("];")
    lines.append("")

    lines.append("/// Replacements for basic patterns (parallel to BASIC_PATTERNS).")
    lines.append("pub(crate) static BASIC_REPLACEMENTS: &[&str] = &[")
    for r in basic_replacements:
        lines.append(f'    "{rust_str(r)}",')
    lines.append("];")
    lines.append("")

    # --- Math Escaped (default: ambiguous commands need ESCAPE_STR prefix) ---
    lines.append("/// Math escaped patterns: ambiguous commands require escape prefix.")
    lines.append("pub(crate) static MATH_ESCAPED_PATTERNS: &[&str] = &[")
    for cmd, _sym in MATH_ESCAPED:
        if cmd in MATH_NEED_ESCAPE:
            lines.append(f'    "{rust_str(ESCAPE_STR)} {rust_str(cmd)}",')
        else:
            lines.append(f'    "{rust_str(cmd)}",')
    lines.append("];")
    lines.append("")

    lines.append("/// Replacements for math escaped patterns.")
    lines.append("pub(crate) static MATH_ESCAPED_REPLACEMENTS: &[&str] = &[")
    for _cmd, sym in MATH_ESCAPED:
        lines.append(f'    "{rust_str(sym)}",')
    lines.append("];")
    lines.append("")

    # --- Math Mode (activated by trigger phrase, all commands bare) ---
    lines.append(f'/// Trigger phrase that activates math mode (case-insensitive).')
    lines.append(f'pub(crate) const MATH_MODE_TRIGGER: &str = "{rust_str(MATH_MODE_TRIGGER)}";')
    lines.append("")

    lines.append("/// Math mode patterns: all symbols available without escape prefix.")
    lines.append("/// Includes trigger phrase mapped to empty string for stripping.")
    lines.append("pub(crate) static MATH_MODE_PATTERNS: &[&str] = &[")
    lines.append(f'    "{rust_str(MATH_MODE_TRIGGER)}",')
    lines.append(f'    "{rust_str(MATH_MODE_TRIGGER)}, ",')
    lines.append(f'    "{rust_str(MATH_MODE_TRIGGER)} ",')
    for cmd, _sym in MATH_ESCAPED:
        lines.append(f'    "{rust_str(cmd)}",')
    lines.append("];")
    lines.append("")

    lines.append("/// Replacements for math mode patterns.")
    lines.append("pub(crate) static MATH_MODE_REPLACEMENTS: &[&str] = &[")
    lines.append('    "",')  # replacement for trigger phrase
    lines.append('    "",')  # replacement for trigger phrase
    lines.append('    "",')  # replacement for trigger phrase
    for _cmd, sym in MATH_ESCAPED:
        lines.append(f'    "{rust_str(sym)}",')
    lines.append("];")
    lines.append("")

    return "\n".join(lines)


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--write", action="store_true",
                        help="overwrite src-tauri/src/substitution_dicts.rs in-place")
    args = parser.parse_args()

    output = generate()
    if args.write:
        OUTPUT_PATH.write_text(output + "\n")
        print(f"wrote {OUTPUT_PATH}")
    else:
        print(output)
