#!/usr/bin/env python3
"""Generate substitution_dicts.rs from the dictionaries defined below.

Usage:
    python3 scripts/generate_dicts.py > src-tauri/src/substitution_dicts.rs
"""

# ──────────────────────────────────────────────
#  BASIC: spoken punctuation commands → symbols
# ──────────────────────────────────────────────
# Each (command, symbol) pair generates TWO entries:
#   "literal <command>" → "<command>"   (escape hatch)
#   "<command>"         → "<symbol>"    (the substitution)

BASIC_COMMANDS = [
    ("comma",             ","),
    ("period",            "."),
    ("tab",               "\t"),
    ("line break",        "\n"),
    ("open quote",        '"'),
    ("close quote",       '"'),
    ("open paren",        "("),
    ("close paren",       ")"),
    ("open bracket",      "["),
    ("close bracket",     "]"),
    ("exclamation point", "!"),
    ("question mark",     "?"),
    ("colon",             ":"),
    ("semicolon",         ";"),
    ("dot dot dot",       "\u2026"),  # …
]

# ──────────────────────────────────────────────
#  PECULIAR: special character names → symbols
# ──────────────────────────────────────────────

PECULIAR = [
    ("alpha", "\u03B1"),  # α
    ("beta",  "\u03B2"),  # β
]


def rust_str(s: str) -> str:
    """Escape a string for a Rust string literal."""
    return (
        s.replace("\\", "\\\\")
        .replace('"', '\\"')
        .replace("\t", "\\t")
        .replace("\n", "\\n")
    )


def generate() -> str:
    lines = [
        "// @generated by scripts/generate_dicts.py — do not edit by hand.",
        "",
    ]

    # --- Basic ---
    basic_patterns = []
    basic_replacements = []

    # Escape hatches first ("literal X" → word X)
    for cmd, _sym in BASIC_COMMANDS:
        basic_patterns.append(f"literal {cmd}")
        basic_replacements.append(cmd)

    # Bare commands ("X" → symbol)
    for cmd, sym in BASIC_COMMANDS:
        basic_patterns.append(cmd)
        basic_replacements.append(sym)

    lines.append("/// Basic substitution patterns: spoken punctuation commands.")
    lines.append("/// Includes \"literal X\" escape hatches.")
    lines.append("pub(crate) static BASIC_PATTERNS: &[&str] = &[")
    for p in basic_patterns:
        lines.append(f'    "{rust_str(p)}",')
    lines.append("];")
    lines.append("")

    lines.append("/// Replacements for basic patterns (parallel to BASIC_PATTERNS).")
    lines.append("pub(crate) static BASIC_REPLACEMENTS: &[&str] = &[")
    for r in basic_replacements:
        lines.append(f'    "{rust_str(r)}",')
    lines.append("];")
    lines.append("")

    # --- Peculiar ---
    lines.append("/// Peculiar substitution patterns: special character names.")
    lines.append("pub(crate) static PECULIAR_PATTERNS: &[&str] = &[")
    for cmd, _sym in PECULIAR:
        lines.append(f'    "{rust_str(cmd)}",')
    lines.append("];")
    lines.append("")

    lines.append("/// Replacements for peculiar patterns (parallel to PECULIAR_PATTERNS).")
    lines.append("pub(crate) static PECULIAR_REPLACEMENTS: &[&str] = &[")
    for _cmd, sym in PECULIAR:
        lines.append(f'    "{rust_str(sym)}",')
    lines.append("];")
    lines.append("")

    return "\n".join(lines)


if __name__ == "__main__":
    print(generate())
