//! Deterministic text substitution for spoken commands.
//!
//! Uses Aho-Corasick finite state automata to replace spoken punctuation
//! and special character names with their symbol equivalents in a single pass.
//! Each automaton is compiled once on first use via `LazyLock`.
//!
//! Dictionaries are defined in `substitution_dicts.rs` (generated by
//! `scripts/generate_dicts.py`).

use aho_corasick::{AhoCorasick, MatchKind};
use std::sync::LazyLock;

#[path = "substitution_dicts.rs"]
mod substitution_dicts;

struct SubstitutionSet {
    ac: AhoCorasick,
    replacements: &'static [&'static str],
}

static BASIC: LazyLock<SubstitutionSet> = LazyLock::new(|| {
    let ac = AhoCorasick::builder()
        .ascii_case_insensitive(true)
        .match_kind(MatchKind::LeftmostLongest)
        .build(substitution_dicts::BASIC_PATTERNS)
        .expect("basic substitution patterns are valid");
    SubstitutionSet {
        ac,
        replacements: substitution_dicts::BASIC_REPLACEMENTS,
    }
});

static MATH_ESCAPED: LazyLock<SubstitutionSet> = LazyLock::new(|| {
    let ac = AhoCorasick::builder()
        .ascii_case_insensitive(true)
        .match_kind(MatchKind::LeftmostLongest)
        .build(substitution_dicts::MATH_ESCAPED_PATTERNS)
        .expect("math escaped substitution patterns are valid");
    SubstitutionSet {
        ac,
        replacements: substitution_dicts::MATH_ESCAPED_REPLACEMENTS,
    }
});

static MATH_MODE: LazyLock<SubstitutionSet> = LazyLock::new(|| {
    let ac = AhoCorasick::builder()
        .ascii_case_insensitive(true)
        .match_kind(MatchKind::LeftmostLongest)
        .build(substitution_dicts::MATH_MODE_PATTERNS)
        .expect("math mode substitution patterns are valid");
    SubstitutionSet {
        ac,
        replacements: substitution_dicts::MATH_MODE_REPLACEMENTS,
    }
});

/// Apply text substitutions to STT output.
///
/// Runs basic substitutions first (if enabled), then math (if enabled).
/// Returns the input unchanged (no allocation) if both flags are false.
pub fn apply_substitutions(text: &str, basic: bool, math: bool) -> String {
    if !basic && !math {
        return text.to_string();
    }

    let mut result = if basic {
        BASIC.ac.replace_all(text, BASIC.replacements)
    } else {
        text.to_string()
    };

    if math {
        // "math mode" trigger phrase → use bare patterns (no escape prefix needed).
        // Otherwise use escaped patterns (ambiguous commands need "slash" prefix).
        let set = if result.to_ascii_lowercase().contains(substitution_dicts::MATH_MODE_TRIGGER) {
            &*MATH_MODE
        } else {
            &*MATH_ESCAPED
        };
        result = set.ac.replace_all(&result, set.replacements);
    }

    result
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn basic_comma() {
        let out = apply_substitutions("hello comma world", true, false);
        assert_eq!(out, "hello, world");
    }

    #[test]
    fn basic_period() {
        let out = apply_substitutions("end of sentence period", true, false);
        assert_eq!(out, "end of sentence.");
    }

    #[test]
    fn escape_hatch() {
        let input = format!("the word {} comma is special", substitution_dicts::ESCAPE_STR);
        let out = apply_substitutions(&input, true, false);
        assert_eq!(out, "the word comma is special");
    }

    #[test]
    fn case_insensitive() {
        let out = apply_substitutions("Hello COMMA World", true, false);
        assert_eq!(out, "Hello, World");
    }

    #[test]
    fn math_escaped() {
        let esc = substitution_dicts::ESCAPE_STR;
        let input = format!("{esc} alpha and {esc} beta particles");
        let out = apply_substitutions(&input, false, true);
        assert_eq!(out, "α and β particles");
    }

    #[test]
    fn math_escaped_bare_word_unchanged() {
        let out = apply_substitutions("alpha and beta particles", false, true);
        assert_eq!(out, "alpha and beta particles");
    }

    #[test]
    fn math_mode_strips_trigger() {
        let out = apply_substitutions("math mode for all x in naturals", false, true);
        assert_eq!(out, " ∀ x ∈ ℕ");
    }

    #[test]
    fn math_mode_case_insensitive_trigger() {
        let out = apply_substitutions("Math Mode alpha", false, true);
        assert_eq!(out, " α");
    }

    #[test]
    fn both_enabled() {
        let esc = substitution_dicts::ESCAPE_STR;
        let input = format!("{esc} alpha comma {esc} beta");
        let out = apply_substitutions(&input, true, true);
        assert_eq!(out, "α, β");
    }

    #[test]
    fn neither_enabled() {
        let out = apply_substitutions("comma period alpha", false, false);
        assert_eq!(out, "comma period alpha");
    }

    #[test]
    fn dot_dot_dot() {
        let out = apply_substitutions("thinking dot dot dot yeah", true, false);
        assert_eq!(out, "thinking… yeah");
    }

    #[test]
    fn multiple_substitutions() {
        let out = apply_substitutions(
            "dear sir comma I have a question mark",
            true,
            false,
        );
        assert_eq!(out, "dear sir, I have a?");
    }
}
