// @generated by scripts/generate_dicts.py — do not edit by hand.

#[cfg(test)]
/// Escape token, for use in Rust tests.
pub(crate) const ESCAPE_STR: &str = "slash";
/// Basic substitution patterns: spoken punctuation commands.
/// Includes "slash X" escape hatches.
pub(crate) static BASIC_PATTERNS: &[&str] = &[
    "slash comma",
    "slash period",
    "slash tab",
    "slash line break",
    "slash open quote",
    "slash close quote",
    "slash open paren",
    "slash close paren",
    "slash open bracket",
    "slash close bracket",
    "slash exclamation point",
    "slash question mark",
    "slash colon",
    "slash semicolon",
    "slash dot dot dot",
    "slash backslash",
    "slash forward slash",
    " comma",
    " period",
    "tab",
    "line break",
    "open quote",
    " close quote",
    "open paren",
    " close paren",
    "open bracket",
    " close bracket",
    " exclamation point",
    " question mark",
    " colon",
    " semicolon",
    " dot dot dot",
    "backslash",
    "forward slash",
    ", comma",
    ". period",
    "? question mark",
];

/// Replacements for basic patterns (parallel to BASIC_PATTERNS).
pub(crate) static BASIC_REPLACEMENTS: &[&str] = &[
    "comma",
    "period",
    "tab",
    "line break",
    "open quote",
    "close quote",
    "open paren",
    "close paren",
    "open bracket",
    "close bracket",
    "exclamation point",
    "question mark",
    "colon",
    "semicolon",
    "dot dot dot",
    "backslash",
    "forward slash",
    ",",
    ".",
    "\t",
    "\n",
    "\"",
    "\"",
    "(",
    ")",
    "[",
    "]",
    "!",
    "?",
    ":",
    ";",
    "…",
    "\\",
    "/",
    ",",
    ".",
    "?",
];

/// Math escaped patterns: ambiguous commands require escape prefix.
pub(crate) static MATH_ESCAPED_PATTERNS: &[&str] = &[
    "slash alpha",
    "slash beta",
    "right arrow",
    "slash for all",
    "slash exists",
    "slash cap",
    "slash cup",
    "slash in",
    "slash integers",
    "slash naturals",
    "slash reals",
    "slash greater than",
    "slash less than",
    "slash at least",
    "slash at most",
];

/// Replacements for math escaped patterns.
pub(crate) static MATH_ESCAPED_REPLACEMENTS: &[&str] = &[
    "α",
    "β",
    "⟶",
    "∀",
    "∃",
    "⋂",
    "⋃",
    "∈",
    "ℤ",
    "ℕ",
    "ℝ",
    ">",
    "<",
    "≥",
    "≤",
];

/// Trigger phrase that activates math mode (case-insensitive).
pub(crate) const MATH_MODE_TRIGGER: &str = "math mode";

/// Math mode patterns: all symbols available without escape prefix.
/// Includes trigger phrase mapped to empty string for stripping.
pub(crate) static MATH_MODE_PATTERNS: &[&str] = &[
    "math mode",
    "math mode, ",
    "math mode ",
    "alpha",
    "beta",
    "right arrow",
    "for all",
    "exists",
    "cap",
    "cup",
    "in",
    "integers",
    "naturals",
    "reals",
    "greater than",
    "less than",
    "at least",
    "at most",
];

/// Replacements for math mode patterns.
pub(crate) static MATH_MODE_REPLACEMENTS: &[&str] = &[
    "",
    "",
    "",
    "α",
    "β",
    "⟶",
    "∀",
    "∃",
    "⋂",
    "⋃",
    "∈",
    "ℤ",
    "ℕ",
    "ℝ",
    ">",
    "<",
    "≥",
    "≤",
];

