// @generated by scripts/generate_dicts.py — do not edit by hand.

/// Basic substitution patterns: spoken punctuation commands.
/// Includes "literal X" escape hatches.
pub(crate) static BASIC_PATTERNS: &[&str] = &[
    "literal comma",
    "literal period",
    "literal tab",
    "literal line break",
    "literal open quote",
    "literal close quote",
    "literal open paren",
    "literal close paren",
    "literal open bracket",
    "literal close bracket",
    "literal exclamation point",
    "literal question mark",
    "literal colon",
    "literal semicolon",
    "literal dot dot dot",
    "comma",
    "period",
    "tab",
    "line break",
    "open quote",
    "close quote",
    "open paren",
    "close paren",
    "open bracket",
    "close bracket",
    "exclamation point",
    "question mark",
    "colon",
    "semicolon",
    "dot dot dot",
];

/// Replacements for basic patterns (parallel to BASIC_PATTERNS).
pub(crate) static BASIC_REPLACEMENTS: &[&str] = &[
    "comma",
    "period",
    "tab",
    "line break",
    "open quote",
    "close quote",
    "open paren",
    "close paren",
    "open bracket",
    "close bracket",
    "exclamation point",
    "question mark",
    "colon",
    "semicolon",
    "dot dot dot",
    ",",
    ".",
    "\t",
    "\n",
    "\"",
    "\"",
    "(",
    ")",
    "[",
    "]",
    "!",
    "?",
    ":",
    ";",
    "…",
];

/// Peculiar substitution patterns: special character names.
pub(crate) static PECULIAR_PATTERNS: &[&str] = &[
    "alpha",
    "beta",
];

/// Replacements for peculiar patterns (parallel to PECULIAR_PATTERNS).
pub(crate) static PECULIAR_REPLACEMENTS: &[&str] = &[
    "α",
    "β",
];

