//! Deterministic text substitution for spoken commands.
//!
//! Uses Aho-Corasick finite state automata to replace spoken punctuation
//! and special character names with their symbol equivalents in a single pass.
//! Each automaton is compiled once on first use via `LazyLock`.
//!
//! Dictionaries are defined in `substitution_dicts.rs` (generated by
//! `scripts/generate_dicts.py`).

use aho_corasick::{AhoCorasick, MatchKind};
use std::sync::LazyLock;

#[path = "substitution_dicts.rs"]
mod substitution_dicts;

struct SubstitutionSet {
    ac: AhoCorasick,
    replacements: &'static [&'static str],
}

static BASIC: LazyLock<SubstitutionSet> = LazyLock::new(|| {
    let ac = AhoCorasick::builder()
        .ascii_case_insensitive(true)
        .match_kind(MatchKind::LeftmostLongest)
        .build(substitution_dicts::BASIC_PATTERNS)
        .expect("basic substitution patterns are valid");
    SubstitutionSet {
        ac,
        replacements: substitution_dicts::BASIC_REPLACEMENTS,
    }
});

static PECULIAR: LazyLock<SubstitutionSet> = LazyLock::new(|| {
    let ac = AhoCorasick::builder()
        .ascii_case_insensitive(true)
        .match_kind(MatchKind::LeftmostLongest)
        .build(substitution_dicts::PECULIAR_PATTERNS)
        .expect("peculiar substitution patterns are valid");
    SubstitutionSet {
        ac,
        replacements: substitution_dicts::PECULIAR_REPLACEMENTS,
    }
});

/// Apply text substitutions to STT output.
///
/// Runs basic substitutions first (if enabled), then peculiar (if enabled).
/// Returns the input unchanged (no allocation) if both flags are false.
pub fn apply_substitutions(text: &str, basic: bool, peculiar: bool) -> String {
    if !basic && !peculiar {
        return text.to_string();
    }

    let mut result = if basic {
        BASIC.ac.replace_all(text, BASIC.replacements)
    } else {
        text.to_string()
    };

    if peculiar {
        result = PECULIAR.ac.replace_all(&result, PECULIAR.replacements);
    }

    result
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn basic_comma() {
        let out = apply_substitutions("hello comma world", true, false);
        assert_eq!(out, "hello, world");
    }

    #[test]
    fn basic_period() {
        let out = apply_substitutions("end of sentence period", true, false);
        assert_eq!(out, "end of sentence.");
    }

    #[test]
    fn literal_escape() {
        let out = apply_substitutions("the word literal comma is special", true, false);
        assert_eq!(out, "the word comma is special");
    }

    #[test]
    fn case_insensitive() {
        let out = apply_substitutions("Hello COMMA World", true, false);
        assert_eq!(out, "Hello, World");
    }

    #[test]
    fn peculiar_greek() {
        let out = apply_substitutions("alpha and beta particles", false, true);
        assert_eq!(out, "\u{03B1} and \u{03B2} particles");
    }

    #[test]
    fn both_enabled() {
        let out = apply_substitutions("alpha comma beta", true, true);
        assert_eq!(out, "\u{03B1}, \u{03B2}");
    }

    #[test]
    fn neither_enabled() {
        let out = apply_substitutions("comma period alpha", false, false);
        assert_eq!(out, "comma period alpha");
    }

    #[test]
    fn dot_dot_dot() {
        let out = apply_substitutions("thinking dot dot dot yeah", true, false);
        assert_eq!(out, "thinking\u{2026} yeah");
    }

    #[test]
    fn multiple_substitutions() {
        let out = apply_substitutions(
            "dear sir comma I have a question mark",
            true,
            false,
        );
        assert_eq!(out, "dear sir, I have a?");
    }
}
